services:
  transformerlab-api:
    image: transformerlab/api:0.10.2
    container_name: transformerlab-api
    ports:
      - "8338:8338"
    volumes:
      - transformerlab_data_cpu:/root/.transformerlab/
      - /Users/abhimazu/.cache:/root/.cache
      - /Users/abhimazu/.transformerlab/workspace:/root/.transformerlab/workspace
    restart: unless-stopped
    tty: true
    stdin_open: true

volumes:
  transformerlab_data_cpu: