# This workflow will install Python dependencies and run tests

name: Pytest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install uv
        uv pip install pytest pytest-asyncio
        if [ -f requirements-no-gpu.txt ]; then uv pip install -r requirements-no-gpu-uv.txt; fi
    - name: Test with pytest
      run: |
        pytest
